import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>React Practice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className='container text-center p-5'>
          <h1>Welcome to Projects</h1>
          <Link className='btn btn-lg btn-primary mt-4 rounded-0' href="/project-list" >Check Projects List</Link> 
        </main>
    </>
  )
}
