import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>React Practice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className='container text-center p-5'>
          <h1>Welcome to Projects</h1>
        </main>
    </>
  )
}
